language: rust

cache: cargo

matrix:
  include:
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=test
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=common
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=boxxy
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=docker
  - os: linux
    rust: stable
    env:
    - BUILD_MODE=docker-registry
  - os: osx
    rust: stable
    env:
    - BUILD_MODE=test
  - os: osx
    rust: stable
    env:
    - BUILD_MODE=common
  #- os: windows
  #  rust: stable
  #  env:
  #  - BUILD_MODE="windows test"
  - os: windows
    rust: stable
    env:
    - BUILD_MODE="windows common"

before_install:
- ci/setup.sh "$TRAVIS_OS_NAME"
script:
- df -h
- ci/run.sh $BUILD_MODE
- df -h
