[package]
name = "sn0int"
version = "0.1.0"
description = "TODO"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/sn0int"
categories = ["command-line-utilities"]
readme = "README.md"

[workspace]
members = ["sn0int-registry"]

[dependencies]
rustyline = "2"
log = "0.4"
env_logger = "0.5"
hlua-badtouch = "0.4"
structopt = "0.2"
failure = "0.1"
rand = "0.5"
colored = "1.6"
lazy_static = "1.0"
shellwords = "0.1"
publicsuffix = { version="1.5", default-features=false }
diesel = { version = "1.0.0", features = ["sqlite"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }
dirs = "1.0"
url = "1.7"
syscallz = "0.7"
nom = "4.0"
chrootable-https = "0.3.0"
trust-dns-proto = "0.5.0-alpha.1"
hyper = "0.12"
base64 = "0.9"
http = "0.1"
kuchiki = "0.7.2"
serde_urlencoded = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
crossbeam-channel = "0.2"

# https://crates.io/crates/tor_control
