[package]
name = "sn0int"
version = "0.3.0"
description = "OSINT framework and package manager"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/sn0int"
categories = ["command-line-utilities"]
readme = "README.md"

[badges]
travis-ci = { repository = "kpcyrd/sn0int" }

[workspace]
members = ["sn0int-registry/sn0int-common",
           "sn0int-registry"]

[dependencies]
sn0int-common = { version="0.2.0", path="sn0int-registry/sn0int-common" }
rustyline = "2"
log = "0.4"
env_logger = "0.5"
hlua-badtouch = "0.4"
structopt = "0.2"
failure = "0.1"
rand = "0.5"
colored = "1.6"
lazy_static = "1.0"
shellwords = "1.0"
publicsuffix = { version="1.5", default-features=false }
diesel = { version = "1.0.0", features = ["sqlite"] }
diesel_migrations = { version = "1.3.0", features = ["sqlite"] }
dirs = "1.0"
url = "1.7"
nix = "0.11"
chrootable-https = "0.3.4"
trust-dns-proto = "0.5.0"
base64 = "0.10"
kuchiki = "0.7.2"
serde_urlencoded = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
crossbeam-channel = "0.3"
ctrlc = "3.1"
opener = "0.3.0"
separator = "0.3.1"
maplit = "1.0.1"
sloppy-rfc4880 = "0.1.2"
regex = "1.0"
toml = "0.4"
maxminddb = "0.10.0"
tar = "0.4.17"
libflate = "0.1.14"

[target.'cfg(target_os="linux")'.dependencies]
caps = "0.3"
syscallz = "0.7"

[dev-dependencies]
boxxy = "0.8"
